image: docker:stable

services:
  - docker:dind

stages:
    - Build Image
    - Publish Image to DockerHub

docker build:
  stage: Build Image
  script:
    - docker info
    - docker build --cache-from azulinho/toolbox:cache --tag azulinho/toolbox:latest --tag azulinho/toolbox:cache .

docker push:
  stage: Publish Image to DockerHub
  only:
    - master
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push azulinho/toolbox:latest
    - docker push azulinho/toolbox:cache
    - docker image rm azulinho/toobox
