variables:
  IMAGE: thecornershop/toolbox

before_script:
  -  docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
    - Build Image

docker build:
  stage: Build Image
  only:
    - master
  script:
    - docker info
    - docker pull $CI_REGISTRY/$IMAGE:cache
    - docker build --cache-from $CI_REGISTRY/$IMAGE:cache --tag $CI_REGISTRY/$IMAGE:latest --tag $CI_REGISTRY/$IMAGE:cache .
    - docker images
    - docker push $CI_REGISTRY/$IMAGE:latest
    - docker push $CI_REGISTRY/$IMAGE:cache
  tags:
    - archlinux

