image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  REGISTRY: registry.gitlab.com
  IMAGE: thecornershop/toolbox

before_script:
  - docker login registry.gitlab.com

stages:
    - Build Image

docker build:
  stage: Build Image
  only:
    - master
  script:
    - docker info
    - docker pull azulinho/toolbox:cache # TODO: change to gitlab registry
    - docker build --cache-from azulinho/toolbox:cache --tag $REGISTRY/$IMAGE:latest --tag $REGISTRY/$IMAGE:cache .
    - docker images
    - docker push $REGISTRY/$IMAGE:latest
    - docker push $REGISTRY/$IMAGE:cache

