image: docker:git

services:
  - name: docker:dind
    command: ["--experimental"]

variables:
  IMAGE: thecornershop/toolbox

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk add make

stages:
    - Build base image
    - Build middle images
    - Build latest image

make base:
  stage: Build base image
  only:
    - master
  script:
    - make base

make python.2.7.16:
  stage: Build middle images
  only:
    - master
  script:
    - make python.2.7.16

make python.3.4.1:
  stage: Build middle images
  only:
    - master
  script:
    - make python.3.4.1

make python.3.5.5:
  stage: Build middle images
  only:
    - master
  script:
    - make python.3.5.5

make python.3.6.3:
  stage: Build middle images
  only:
    - master
  script:
    - make python.3.6.3

make python.3.6.8:
  stage: Build middle images
  only:
    - master
  script:
    - make python.3.6.8

make python.3.7.4:
  stage: Build middle images
  only:
    - master
  script:
    - make python.3.7.4


make ruby.2.3.3:
  stage: Build middle images
  only:
    - master
  script:
    - make ruby.2.3.3

make ruby.2.4.3:
  stage: Build middle images
  only:
    - master
  script:
    - make ruby.2.4.3

make ruby.2.5.1:
  stage: Build middle images
  only:
    - master
  script:
    - make ruby.2.5.1

make ruby.2.6.3:
  stage: Build middle images
  only:
    - master
  script:
    - make ruby.2.6.3

make latest:
  stage: Build latest image
  only:
    - master
  script:
    - make latest
