image: docker:experimental-dind

variables:
  IMAGE: thecornershop/toolbox

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
    - Build base image
    - Build middle images
    - Build latest image


docker build base:
  stage: Build base image
  services:
    - name: docker:dind
      command: ["--experimental"]
  only:
    - master
  script:
    - make base

docker build python image:
  stage: Build middle images
  services:
    - name: docker:dind
      command: ["--experimental"]
  only:
    - master
  script:
    - make python

docker build ruby image:
  stage: Build middle images
  services:
    - name: docker:dind
      command: ["--experimental"]
  only:
    - master
  script:
    - make ruby

docker build latest:
  stage: Build latest image
  services:
    - name: docker:dind
      command: ["--experimental"]
  only:
    - master
  script:
    - make latest
