image: docker:stable

stages:
    - Build Image
    - Publish Image to DockerHub

docker build:
  stage: Build Image
  script:
    - docker info
    - docker build -t azulinho/toolboox .

docker push:
  stage: Publish Image to DockerHub
  only:
    - master
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push azulinho/toolbox
    - docker image rm azulinho/toobox
